/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseResultsRouteImport } from './routes/case-results'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseResultsRoute = CaseResultsRouteImport.update({
  id: '/case-results',
  path: '/case-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-results': typeof CaseResultsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-results': typeof CaseResultsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-results': typeof CaseResultsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-results'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/practice-areas'
    | '/sitemap.xml'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-results'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/practice-areas'
    | '/sitemap.xml'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-results'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/practice-areas'
    | '/sitemap.xml'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseResultsRoute: typeof CaseResultsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRoute
  PracticeAreasRoute: typeof PracticeAreasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-results': {
      id: '/case-results'
      path: '/case-results'
      fullPath: '/case-results'
      preLoaderRoute: typeof CaseResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseResultsRoute: CaseResultsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRoute,
  PracticeAreasRoute: PracticeAreasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
